
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "mazharenko.AoCAgent"
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule:
      interval: "monthly"

